//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreFront.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public int CategoryID { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public int ItemsPerUnit { get; set; }
        public int UnitsOnOrder { get; set; }
        public Nullable<int> UnitsSold { get; set; }
        public int UnitsInStock { get; set; }
        public int StockStatusID { get; set; }
        public string Image { get; set; }
    
        public virtual ProductCategories ProductCategory { get; set; }
        public virtual StockStatuses StockStatus { get; set; }
    }
}
